### ISSUE TITLE
fix documentation

### ISSUE THREAD

**Issue by rockpapergoat** [rockpapergoat/threatstack-puppet#1]
- update with windows params and usage
- update any other stuff that's missing
- include examples, if possible

**Comment by emmeowzing** [comment]
Documentation also needs to be updated to reflect support for Amazon Linux 1.

**Comment by rockpapergoat** [comment]
@bjd2385 i think the amazon linux 1 & 2 doc stuff was resolved in the main threatstack-puppet repo, so i'm closing this for now. will add some issues in that repo instead of here. i was using this sort of as reminders to get back to a few things after a flurry of activity.
